#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/bootstrap_xlotyl_contract_env.sh [--no-install] [--no-build] [--skip-bun]

Bootstraps the local Stoneforge + XLOTYL contract test toolchain.

Defaults assume this layout:

  XLOTYL/
    .local/       generated shared tool/env/cache state
    xlotyl/       XLOTYL/xlotyl checkout
    stoneforge/   this repository

Environment overrides:
  XLOTYL_WORKSPACE_ROOT  Parent workspace root; default is the parent of this repo.
  XLOTYL_REPO_ROOT       XLOTYL checkout; default is $XLOTYL_WORKSPACE_ROOT/xlotyl.
  XLOTYL_LOCAL_ROOT      Shared generated state root; default is $XLOTYL_WORKSPACE_ROOT/.local.

Generated env:
  $XLOTYL_LOCAL_ROOT/env/xlotyl-stoneforge-contract.env
USAGE
}

log() {
  printf '[stoneforge-contract-env] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'error: required command not found: %s\n' "$1" >&2
    exit 1
  fi
}

run_install=1
run_build=1
install_bun=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --no-install)
      run_install=0
      shift
      ;;
    --no-build)
      run_build=0
      shift
      ;;
    --skip-bun)
      install_bun=0
      shift
      ;;
    *)
      printf 'error: unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_ROOT="${XLOTYL_WORKSPACE_ROOT:-$(cd -- "$REPO_ROOT/.." && pwd)}"
LOCAL_ROOT="${XLOTYL_LOCAL_ROOT:-$WORKSPACE_ROOT/.local}"
XLOTYL_ROOT="${XLOTYL_REPO_ROOT:-$WORKSPACE_ROOT/xlotyl}"

ENV_DIR="$LOCAL_ROOT/env"
ENV_FILE="$ENV_DIR/xlotyl-stoneforge-contract.env"
NPM_PREFIX="$LOCAL_ROOT/npm-global"
NPM_CACHE="$LOCAL_ROOT/npm-cache"
PNPM_STORE="$LOCAL_ROOT/pnpm-store"
BUN_INSTALL_DIR="$LOCAL_ROOT/bun"
BUN_BIN="$BUN_INSTALL_DIR/bin/bun"
NPM_BIN="$NPM_PREFIX/bin/npm"
PNPM_BIN="$NPM_PREFIX/bin/pnpm"

require_cmd node
require_cmd npm

PNPM_VERSION="$(
  REPO_ROOT="$REPO_ROOT" node -e 'const pm=require(process.env.REPO_ROOT + "/package.json").packageManager || "pnpm@8.15.5"; console.log(pm.startsWith("pnpm@") ? pm.slice(5) : "8.15.5")'
)"
NPM_VERSION="$(
  XLOTYL_ROOT="$XLOTYL_ROOT" node -e 'try { const pm=require(process.env.XLOTYL_ROOT + "/package.json").packageManager || "npm@latest"; console.log(pm.startsWith("npm@") ? pm.slice(4) : "latest") } catch { console.log("latest") }'
)"

mkdir -p "$ENV_DIR" "$NPM_PREFIX" "$NPM_CACHE" "$PNPM_STORE" "$BUN_INSTALL_DIR"

export NPM_CONFIG_CACHE="$NPM_CACHE"
if [[ "$run_install" -eq 1 ]]; then
  log "Installing npm@$NPM_VERSION and pnpm@$PNPM_VERSION under $NPM_PREFIX"
  npm install --prefix "$NPM_PREFIX" "npm@$NPM_VERSION" "pnpm@$PNPM_VERSION"

  if [[ "$install_bun" -eq 1 && ! -x "$BUN_BIN" ]]; then
    require_cmd curl
    log "Installing Bun under $BUN_INSTALL_DIR"
    curl -fsSL https://bun.sh/install | BUN_INSTALL="$BUN_INSTALL_DIR" bash
  elif [[ -x "$BUN_BIN" ]]; then
    log "Using Bun at $BUN_BIN"
  fi

  log "Installing Stoneforge pnpm workspace dependencies into $REPO_ROOT/node_modules"
  (cd "$REPO_ROOT" && "$PNPM_BIN" install --frozen-lockfile --store-dir "$PNPM_STORE")

  if [[ -d "$XLOTYL_ROOT" && -f "$XLOTYL_ROOT/package-lock.json" ]]; then
    log "Installing XLOTYL npm workspace dependencies into $XLOTYL_ROOT/node_modules"
    (cd "$XLOTYL_ROOT" && "$NPM_BIN" ci)
  else
    log "XLOTYL checkout not found at $XLOTYL_ROOT; set XLOTYL_REPO_ROOT to build the decision provider"
  fi
fi

if [[ "$run_build" -eq 1 ]]; then
  log "Building Stoneforge Smithy sf.js"
  (cd "$REPO_ROOT" && "$PNPM_BIN" turbo run build --filter=@stoneforge/smithy)

  if [[ -d "$XLOTYL_ROOT" && -f "$XLOTYL_ROOT/package.json" ]]; then
    log "Building @xlotyl/core-dev-services"
    (cd "$XLOTYL_ROOT" && "$NPM_BIN" run build -w @xlotyl/core-dev-services)
  fi
fi

{
  printf '# Generated by %s\n' "$0"
  printf 'export XLOTYL_WORKSPACE_ROOT=%q\n' "$WORKSPACE_ROOT"
  printf 'export XLOTYL_REPO_ROOT=%q\n' "$XLOTYL_ROOT"
  printf 'export STONEFORGE_REPO_ROOT=%q\n' "$REPO_ROOT"
  printf 'export XLOTYL_LOCAL_ROOT=%q\n' "$LOCAL_ROOT"
  printf 'export NPM_CONFIG_CACHE=%q\n' "$NPM_CACHE"
  printf 'export NPM_CONFIG_PREFIX=%q\n' "$NPM_PREFIX"
  printf 'export PNPM_STORE_DIR=%q\n' "$PNPM_STORE"
  printf 'export BUN_INSTALL=%q\n' "$BUN_INSTALL_DIR"
  printf 'export STONEFORGE_SF_BIN=%q\n' "$REPO_ROOT/packages/smithy/dist/bin/sf.js"
  printf 'export XLOTYL_DECISION_MODULE=%q\n' "$XLOTYL_ROOT/services/core-dev-services/dist/stoneforge/daemon-decision.js"
  printf 'export PATH=%q:%q:"$PATH"\n' "$NPM_PREFIX/bin" "$BUN_INSTALL_DIR/bin"
} > "$ENV_FILE"

log "Wrote $ENV_FILE"
log "Run: source $ENV_FILE"
log "Then: pnpm --filter @stoneforge/smithy test:xlotyl-daemon-decision"
